version: '3'

services:
  app1:
    build: .
    container_name: app1

  app2:
    build: .
    container_name: app2

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
